name: Daily Auto Commit

on:
  schedule:
    # Runs every day at 09:00 UTC
    - cron: '0 9 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make a daily update - 24f2006531@ds.study.iitm.ac.in
      run: |
        echo "Daily update: $(date)" >> daily-log.txt
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add daily-log.txt
        git commit -m "chore: daily log update $(date)"
        git push
